import { useEffect, useMemo, useState } from 'react'
import { addStockMovement, createOrder, createProduct, createRecipe, currentUser, fetchCategories, fetchInventory, fetchOrders, fetchProducts, fetchReorderItems, fetchRecipes, login, produceBatch, sendReceipt, updateProduct, updateReorderLevel, type Category, type InventoryItem, type Order, type Product, type Recipe, type User } from './lib/api'
import { clearToken } from './lib/api'
import './styles.css'

type CartLine = { product: Product; quantity: number }
const money = (value: number) => `$${value.toFixed(2)}`

export default function App() {
  const [user, setUser] = useState<User | null>(null)
  const [loginForm, setLoginForm] = useState({ username: 'cashier', password: 'cashier123' })
  const [loginError, setLoginError] = useState('')
  const [section, setSection] = useState<'pos' | 'inventory' | 'catalog' | 'reorder' | 'production' | 'orders'>('pos')
  const [products, setProducts] = useState<Product[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [inventory, setInventory] = useState<InventoryItem[]>([])
  const [reorders, setReorders] = useState<InventoryItem[]>([])
  const [orders, setOrders] = useState<Order[]>([])
  const [recipes, setRecipes] = useState<Recipe[]>([])
  const [cart, setCart] = useState<CartLine[]>([])
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')
  const [productForm, setProductForm] = useState({ sku: '', name: '', categoryId: 0, price: '', unit: 'each', inventoryMode: 'stocked' })
  const [stockForm, setStockForm] = useState({ productId: 0, quantity: '', reorderLevel: '' })
  const [productionForm, setProductionForm] = useState({ name: '', outputProductId: 0, ingredientProductId: 0, quantityPerUnit: '', batchQuantity: '', expiresAt: '' })

  const canManage = user?.role === 'admin' || user?.role === 'manager'
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600) }
  const loadData = async () => {
    const [loadedProducts, loadedCategories, loadedInventory, loadedOrders] = await Promise.all([fetchProducts(), fetchCategories(), fetchInventory(), fetchOrders()])
    setProducts(loadedProducts); setCategories(loadedCategories); setInventory(loadedInventory); setOrders(loadedOrders)
    if (canManage) { setReorders(await fetchReorderItems()); setRecipes(await fetchRecipes()) }
  }
  useEffect(() => { currentUser().then(setUser).catch(() => setUser(null)) }, [])
  useEffect(() => { if (user) loadData().catch((error) => notify(error.message)) }, [user])

  const filteredProducts = useMemo(() => products.filter((product) => `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase())), [products, query])
  const subtotal = cart.reduce((sum, line) => sum + line.product.price * line.quantity, 0)
  const tax = Math.round(subtotal * 0.0825 * 100) / 100
  const total = subtotal + tax
  const addToCart = (product: Product) => setCart((current) => { const existing = current.find((line) => line.product.id === product.id); if (product.stock <= (existing?.quantity ?? 0)) { notify(`${product.name} has insufficient stock`); return current }; return existing ? current.map((line) => line.product.id === product.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { product, quantity: 1 }] })
  const changeQuantity = (productId: number, delta: number) => setCart((current) => current.map((line) => line.product.id === productId ? { ...line, quantity: line.quantity + delta } : line).filter((line) => line.quantity > 0))

  const submitLogin = async (event: React.FormEvent) => { event.preventDefault(); try { setLoginError(''); setUser(await login(loginForm.username, loginForm.password)) } catch { setLoginError('Invalid credentials or API is offline') } }
  const submitProduct = async (event: React.FormEvent) => { event.preventDefault(); try { const input = { sku: productForm.sku, name: productForm.name, categoryId: productForm.categoryId, price: Number(productForm.price), unit: productForm.unit, active: true, inventoryMode: productForm.inventoryMode }; await createProduct(input); setProductForm({ sku: '', name: '', categoryId: 0, price: '', unit: 'each', inventoryMode: 'stocked' }); await loadData(); notify('Item added to catalog') } catch (error) { notify(error instanceof Error ? error.message : 'Could not add item') } }
  const submitStock = async (event: React.FormEvent) => { event.preventDefault(); try { await addStockMovement({ productId: stockForm.productId, locationId: user!.locationId, quantity: Number(stockForm.quantity), type: 'stock-receipt', reason: 'Phase 1 receiving' }); if (stockForm.reorderLevel) await updateReorderLevel(stockForm.productId, user!.locationId, Number(stockForm.reorderLevel)); await loadData(); setStockForm({ productId: 0, quantity: '', reorderLevel: '' }); notify('Inventory updated') } catch (error) { notify(error instanceof Error ? error.message : 'Could not update inventory') } }
  const completeSale = async () => { try { const order = await createOrder({ registerId: 'register-03', orderType: 'counter-sale', paymentMethod: 'card', lines: cart.map((line) => ({ productId: line.product.id, quantity: line.quantity })) }); const printed = await sendReceipt(order); setCart([]); await loadData(); notify(printed ? `Sale ${order.orderNumber} completed and receipt queued` : `Sale ${order.orderNumber} completed; printer unavailable`) } catch (error) { notify(error instanceof Error ? error.message : 'Sale failed') } }
  const submitProduction = async (event: React.FormEvent) => { event.preventDefault(); try { const recipe = await createRecipe({ name: productionForm.name, outputProductId: productionForm.outputProductId, ingredients: [{ productId: productionForm.ingredientProductId, quantityPerUnit: Number(productionForm.quantityPerUnit), unit: 'each' }] }); await produceBatch({ recipeId: recipe.id, locationId: user!.locationId, quantityProduced: Number(productionForm.batchQuantity), expiresAt: productionForm.expiresAt ? new Date(productionForm.expiresAt).toISOString() : undefined }); await loadData(); notify('Prepared batch produced and ingredient stock deducted') } catch (error) { notify(error instanceof Error ? error.message : 'Production failed') } }

  if (!user) return <div className="login-screen"><div className="login-card"><div className="brand-mark">CP</div><p className="eyebrow">Counterpoint operations</p><h1>Sign in to continue</h1><p className="login-copy">Use your assigned role to access POS, inventory, and catalog operations.</p><form onSubmit={submitLogin}><label>Username<input value={loginForm.username} onChange={(event) => setLoginForm({ ...loginForm, username: event.target.value })} /></label><label>Password<input type="password" value={loginForm.password} onChange={(event) => setLoginForm({ ...loginForm, password: event.target.value })} /></label>{loginError && <p className="form-error">{loginError}</p>}<button className="primary-button">Sign in</button></form><small>Development accounts: admin / admin123, manager / manager123, cashier / cashier123</small></div></div>

  return <div className="operations-app"><header className="operations-header"><div><div className="brand-line"><span className="brand-mark">CP</span><strong>Counterpoint</strong></div><span className="location-label">Downtown Cafe · Register 03</span></div><div className="session"><span className="online-dot" />{user.displayName}<span className="role-badge">{user.role}</span><button onClick={() => { clearToken(); setUser(null) }}>Sign out</button></div></header><div className="operations-body"><nav className="operations-nav"><p>Workspace</p><button className={section === 'pos' ? 'active' : ''} onClick={() => setSection('pos')}>POS sale</button><button className={section === 'orders' ? 'active' : ''} onClick={() => setSection('orders')}>Sales history</button><p>Inventory</p>{canManage && <><button className={section === 'catalog' ? 'active' : ''} onClick={() => setSection('catalog')}>Catalog</button><button className={section === 'inventory' ? 'active' : ''} onClick={() => setSection('inventory')}>Stock receiving</button><button className={section === 'production' ? 'active' : ''} onClick={() => setSection('production')}>Prepared production</button><button className={section === 'reorder' ? 'active' : ''} onClick={() => setSection('reorder')}>Reorder queue <b>{reorders.length}</b></button></>}</nav><main className="operations-main"><div className="page-title"><div><p className="eyebrow">{section === 'pos' ? 'Counter sale' : section.replace('-', ' ')}</p><h1>{section === 'pos' ? 'Point of sale' : section === 'orders' ? 'Sales history' : section === 'catalog' ? 'Product catalog' : section === 'inventory' ? 'Stock receiving' : section === 'production' ? 'Prepared production' : 'Items to reorder'}</h1></div><span className="data-status">PostgreSQL · Live data</span></div>{section === 'pos' && <PosView products={filteredProducts} query={query} setQuery={setQuery} addToCart={addToCart} cart={cart} changeQuantity={changeQuantity} clearCart={() => setCart([])} subtotal={subtotal} tax={tax} total={total} completeSale={completeSale} />}{section === 'catalog' && <CatalogView products={products} categories={categories} form={productForm} setForm={setProductForm} submit={submitProduct} />}{section === 'inventory' && <InventoryView inventory={inventory} products={products} form={stockForm} setForm={setStockForm} submit={submitStock} />}{section === 'production' && <ProductionView products={products} recipes={recipes} form={productionForm} setForm={setProductionForm} submit={submitProduction} />}{section === 'reorder' && <ReorderView items={reorders} />}{section === 'orders' && <OrdersView orders={orders} />}</main></div>{notice && <div className="toast">{notice}</div>}</div>
}

function PosView({ products, query, setQuery, addToCart, cart, changeQuantity, clearCart, subtotal, tax, total, completeSale }: { products: Product[]; query: string; setQuery: (value: string) => void; addToCart: (product: Product) => void; cart: CartLine[]; changeQuantity: (id: number, delta: number) => void; clearCart: () => void; subtotal: number; tax: number; total: number; completeSale: () => void }) { return <div className="pos-layout"><section><input className="wide-search" placeholder="Search SKU or product name" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="real-product-grid">{products.map((product) => <button className={`real-product ${product.stock <= 0 ? 'out-of-stock' : ''}`} key={product.id} disabled={product.stock <= 0} onClick={() => addToCart(product)}><span>{product.sku}</span><strong>{product.name}</strong><small>{money(product.price)} · {product.stock} {product.unit} available</small></button>)}</div>{!products.length && <div className="empty-panel">No catalog items match this search.</div>}</section><aside className="sale-panel"><div className="panel-heading"><div><p className="eyebrow">Current sale</p><h2>{cart.length ? `${cart.reduce((sum, line) => sum + line.quantity, 0)} items` : 'Empty sale'}</h2></div><button onClick={clearCart}>Clear</button></div><div className="sale-lines">{cart.map((line) => <div className="sale-line" key={line.product.id}><div><strong>{line.product.name}</strong><small>{money(line.product.price)} each</small></div><div className="stepper"><button onClick={() => changeQuantity(line.product.id, -1)}>−</button><span>{line.quantity}</span><button disabled={line.quantity >= line.product.stock} onClick={() => changeQuantity(line.product.id, 1)}>+</button></div><b>{money(line.product.price * line.quantity)}</b></div>)}</div><div className="sale-total"><span>Subtotal</span><b>{money(subtotal)}</b><span>Tax</span><b>{money(tax)}</b><strong>Total</strong><strong>{money(total)}</strong></div><button className="primary-button" disabled={!cart.length} onClick={completeSale}>Complete sale · {money(total)}</button></aside></div> }
function CatalogView({ products, categories, form, setForm, submit }: { products: Product[]; categories: Category[]; form: { sku: string; name: string; categoryId: number; price: string; unit: string; inventoryMode: string }; setForm: (form: { sku: string; name: string; categoryId: number; price: string; unit: string; inventoryMode: string }) => void; submit: (event: React.FormEvent) => void }) { return <div className="management-grid"><form className="form-panel" onSubmit={submit}><h2>Add catalog item</h2><p>New items are stored in PostgreSQL and immediately available to POS.</p><label>SKU<input required value={form.sku} onChange={(event) => setForm({ ...form, sku: event.target.value })} /></label><label>Item name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Category<select required value={form.categoryId || ''} onChange={(event) => setForm({ ...form, categoryId: Number(event.target.value) })}><option value="" disabled>Choose category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Inventory mode<select value={form.inventoryMode} onChange={(event) => setForm({ ...form, inventoryMode: event.target.value })}><option value="stocked">Purchased / stocked item</option><option value="prepared">Prepared menu item</option></select></label><label>Sale price<input required type="number" min="0" step="0.01" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} /></label><label>Unit<input required value={form.unit} onChange={(event) => setForm({ ...form, unit: event.target.value })} /></label><button className="primary-button">Add item</button></form><DataTable title="Current catalog" headers={['SKU', 'Name', 'Category', 'Mode', 'Price']} rows={products.map((product) => [product.sku, product.name, product.category, product.inventoryMode, money(product.price)])} /></div> }
function InventoryView({ inventory, products, form, setForm, submit }: { inventory: InventoryItem[]; products: Product[]; form: { productId: number; quantity: string; reorderLevel: string }; setForm: (form: { productId: number; quantity: string; reorderLevel: string }) => void; submit: (event: React.FormEvent) => void }) { return <div className="management-grid"><form className="form-panel" onSubmit={submit}><h2>Receive stock</h2><p>Every receipt creates an auditable stock movement.</p><label>Item<select required value={form.productId} onChange={(event) => setForm({ ...form, productId: Number(event.target.value) })}><option value={0}>Choose item</option>{products.map((product) => <option key={product.id} value={product.id}>{product.sku} · {product.name}</option>)}</select></label><label>Quantity received<input required type="number" min="0.001" step="0.001" value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} /></label><label>Reorder level<input type="number" min="0" step="0.001" value={form.reorderLevel} onChange={(event) => setForm({ ...form, reorderLevel: event.target.value })} /></label><button className="primary-button">Post stock receipt</button></form><DataTable title="Location stock" headers={['SKU', 'Item', 'On hand', 'Reorder', 'Status']} rows={inventory.map((item) => [item.sku, item.productName, `${item.onHand} ${item.unit}`, `${item.reorderLevel}`, item.needsReorder ? 'REORDER' : 'Healthy'])} /></div> }
function ProductionView({ products, recipes, form, setForm, submit }: { products: Product[]; recipes: Recipe[]; form: { name: string; outputProductId: number; ingredientProductId: number; quantityPerUnit: string; batchQuantity: string; expiresAt: string }; setForm: (form: { name: string; outputProductId: number; ingredientProductId: number; quantityPerUnit: string; batchQuantity: string; expiresAt: string }) => void; submit: (event: React.FormEvent) => void }) { const prepared = products.filter((product) => product.inventoryMode === 'prepared'); const raw = products.filter((product) => product.inventoryMode !== 'prepared'); return <div className="management-grid"><form className="form-panel" onSubmit={submit}><h2>Produce prepared menu item</h2><p>Consume raw stock and create sellable prepared stock in one transaction.</p><label>Batch name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Prepared item<select required value={form.outputProductId} onChange={(event) => setForm({ ...form, outputProductId: Number(event.target.value) })}><option value={0}>Choose menu item</option>{prepared.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Raw ingredient<select required value={form.ingredientProductId} onChange={(event) => setForm({ ...form, ingredientProductId: Number(event.target.value) })}><option value={0}>Choose ingredient</option>{raw.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>Ingredient quantity per item<input required type="number" min="0.001" step="0.001" value={form.quantityPerUnit} onChange={(event) => setForm({ ...form, quantityPerUnit: event.target.value })} /></label><label>Batch quantity<input required type="number" min="1" step="1" value={form.batchQuantity} onChange={(event) => setForm({ ...form, batchQuantity: event.target.value })} /></label><label>Expiry<input type="datetime-local" value={form.expiresAt} onChange={(event) => setForm({ ...form, expiresAt: event.target.value })} /></label><button className="primary-button">Produce batch</button></form><DataTable title="Recipes" headers={['Recipe', 'Output', 'Ingredients']} rows={recipes.map((recipe) => [recipe.name, products.find((product) => product.id === recipe.outputProductId)?.name ?? 'Unknown', `${recipe.ingredients.length}`])} empty="No recipes created yet." /></div> }
function ReorderView({ items }: { items: InventoryItem[] }) { return <DataTable title="Reorder queue" headers={['SKU', 'Item', 'On hand', 'Reorder level', 'Location']} rows={items.map((item) => [item.sku, item.productName, `${item.onHand} ${item.unit}`, `${item.reorderLevel}`, item.locationName])} empty="No items currently need reordering." /> }
function OrdersView({ orders }: { orders: Order[] }) { return <DataTable title="Recent sales" headers={['Order', 'Register', 'Status', 'Total', 'Created']} rows={orders.map((order) => [order.orderNumber, order.registerId, order.status, money(order.total), new Date(order.createdAt).toLocaleString()])} empty="No sales recorded yet." /> }
function DataTable({ title, headers, rows, empty = 'No records found.' }: { title: string; headers: string[]; rows: string[][]; empty?: string }) { return <section className="table-panel"><div className="panel-heading"><h2>{title}</h2><span>{rows.length} records</span></div>{rows.length ? <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div> : <div className="empty-panel">{empty}</div>}</section> }
