import type { PosBootstrap } from './lib/api'

type ProductForm = { sku: string; name: string; categoryId: string; price: string; unit: string; productType: string; hsnCode: string; gstRate: string }

export function CatalogView({ bootstrap, categoryName, setCategoryName, productForm, setProductForm, addCategory, addProduct }: { bootstrap: PosBootstrap; categoryName: string; setCategoryName: (value: string) => void; productForm: ProductForm; setProductForm: (value: ProductForm) => void; addCategory: (event: React.FormEvent) => void; addProduct: (event: React.FormEvent) => void }) {
  return <div className="catalog-admin-grid">
    <form className="form-panel" onSubmit={addCategory}><h2>Add category</h2><p>Categories organize the server-authoritative catalog.</p><label>Name<input required value={categoryName} onChange={event => setCategoryName(event.target.value)} /></label><button className="primary-button">Add category</button></form>
    <form className="form-panel" onSubmit={addProduct}><h2>Add product</h2><p>Prices and tax identity are stored by the API.</p><label>SKU<input required value={productForm.sku} onChange={event => setProductForm({ ...productForm, sku: event.target.value })} /></label><label>Name<input required value={productForm.name} onChange={event => setProductForm({ ...productForm, name: event.target.value })} /></label><label>Category<select required value={productForm.categoryId} onChange={event => setProductForm({ ...productForm, categoryId: event.target.value })}><option value="">Choose category</option>{bootstrap.categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Price<input required type="number" min="0" step="0.01" value={productForm.price} onChange={event => setProductForm({ ...productForm, price: event.target.value })} /></label><label>Unit<input required value={productForm.unit} onChange={event => setProductForm({ ...productForm, unit: event.target.value })} /></label><label>HSN code<input value={productForm.hsnCode} onChange={event => setProductForm({ ...productForm, hsnCode: event.target.value })} /></label><label>GST (%)<input type="number" min="0" step="0.01" value={productForm.gstRate} onChange={event => setProductForm({ ...productForm, gstRate: event.target.value })} /></label><label>CGST (%)<input readOnly value={(Number(productForm.gstRate || 0) / 2).toFixed(2)} /></label><label>SGST (%)<input readOnly value={(Number(productForm.gstRate || 0) / 2).toFixed(2)} /></label><label>Product type<select value={productForm.productType} onChange={event => setProductForm({ ...productForm, productType: event.target.value })}><option value="STOCKED_PRODUCT">Stocked product</option><option value="PREPARED_PRODUCT">Prepared product</option><option value="MENU_ITEM">Menu item</option><option value="MERCHANDISE">Merchandise</option><option value="NON_STOCK">Non-stock</option></select></label><button className="primary-button">Add product</button></form>
    <section className="table-panel catalog-admin-list"><div className="panel-heading"><h2>Catalog</h2><span>{bootstrap.products.length} products</span></div><div className="table-scroll"><table><thead><tr><th>SKU</th><th>Name</th><th>Type</th><th>Price</th><th>Status</th></tr></thead><tbody>{bootstrap.products.map(product => <tr key={product.id}><td>{product.sku}</td><td>{product.name}</td><td>{product.productType}</td><td>{product.price.toFixed(2)}</td><td>{product.active ? 'Active' : 'Inactive'}</td></tr>)}</tbody></table></div></section>
  </div>
}
